[colors]
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black = '#282a36'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#bd93f9'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#f8f8f2'

# Bright colors
[colors.bright]
black = '#44475a'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#bd93f9'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#f8f8f2'

[colors.selection]
background = '#44475a'